version: "3.8"

services:
  app:
    environment:
      - NODE_ENV=development
    volumes:
      - ./:${HOMEDIR}/
      - ${HOMEDIR}/node_modules 
    command: npm run dev
  
  mysql:
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro